//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLib.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjacentNode
    {
        public int NodeId { get; set; }
        public int AdjacentNodeId { get; set; }
    
        public virtual Node Node { get; set; }
    }
}
