//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphLoader.GraphServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Massive", ConfigurationName="GraphServices.IGraphData")]
    public interface IGraphData {
        
        [System.ServiceModel.OperationContractAttribute(Action="Massive/IGraphData/LoadGraph", ReplyAction="Massive/IGraphData/LoadGraphResponse")]
        void LoadGraph(System.Collections.Generic.List<string> graph);
        
        [System.ServiceModel.OperationContractAttribute(Action="Massive/IGraphData/LoadGraph", ReplyAction="Massive/IGraphData/LoadGraphResponse")]
        System.Threading.Tasks.Task LoadGraphAsync(System.Collections.Generic.List<string> graph);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGraphDataChannel : GraphLoader.GraphServices.IGraphData, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GraphDataClient : System.ServiceModel.ClientBase<GraphLoader.GraphServices.IGraphData>, GraphLoader.GraphServices.IGraphData {
        
        public GraphDataClient() {
        }
        
        public GraphDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GraphDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GraphDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void LoadGraph(System.Collections.Generic.List<string> graph) {
            base.Channel.LoadGraph(graph);
        }
        
        public System.Threading.Tasks.Task LoadGraphAsync(System.Collections.Generic.List<string> graph) {
            return base.Channel.LoadGraphAsync(graph);
        }
    }
}
